services:
  demo:
  wmts:
  wms:
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']

layers:
  - name: combined_layers
    title: Combined Map Layers
    sources: [rivertiles_cache, stuttgart_map_cache, luftbild_cache]
    legend:
      url: https://example.com/legend.png  # Optional legend

  - name: luftbild
    title: Aktuelle Luftbild
    sources: [luftbild_cache]

  - name: osm_bright
    title: OpenStreetMap Bright Layer
    sources: [osm_bright_cache]

caches:
  rivertiles_cache:
    grids: [osm_bright_grid]
    sources: [rivertiles_source]
    format: image/png

  stuttgart_map_cache:
    grids: [osm_bright_grid]
    sources: [stuttgart_map_source]
    format: image/png

  luftbild_cache:
    grids: [osm_bright_grid]
    sources: [luftbild_source]
    format: image/png

  osm_bright_cache:
    grids: [osm_bright_grid]
    sources: [osm_bright_source]
    format: image/png

sources:
  rivertiles_source:
    type: tile
    url: https://neckarinsel.s3.eu-north-1.amazonaws.com/assets/tiles/rivertiles/{z}/{x}/{y}.png
    grid: osm_bright_grid

  stuttgart_map_source:
    type: tile
    url: https://neckarinsel.s3.eu-north-1.amazonaws.com/assets/tiles/stuttgart_map/{z}/{x}/{y}.png
    grid: osm_bright_grid

  luftbild_source:
    type: wms
    supported_formats: [png, jpeg]
    supported_srs: ['EPSG:3857', 'EPSG:4326', 'EPSG:25832']
    req:
      url: https://geoserver.stuttgart.de/geoserver/Base/wms
      layers: Base:A62_Luftbild_aktuell_EPSG25832
      transparent: true
    coverage:
      geojson: /mapproxy/masks/stuttgart_mask.geojson
      srs: 'EPSG:3857'

  osm_bright_source:
    type: tile
    url: https://geo.timetochange.today/geoserver/gwc/service/tms/1.0.0/osm:osm_bright@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png
    grid: osm_bright_grid_reverse

grids:
  osm_bright_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw

  osm_bright_grid_reverse:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: sw

globals:
  cache:
    base_dir: './cache_data'
    lock_dir: './cache_data/locks'

  image:
    resampling_method: bilinear
    jpeg_quality: 90
